// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package model

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTabler creates a new instance of MockTabler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTabler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTabler {
	mock := &MockTabler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTabler is an autogenerated mock type for the Tabler type
type MockTabler struct {
	mock.Mock
}

type MockTabler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTabler) EXPECT() *MockTabler_Expecter {
	return &MockTabler_Expecter{mock: &_m.Mock}
}

// TableName provides a mock function for the type MockTabler
func (_mock *MockTabler) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTabler_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type MockTabler_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *MockTabler_Expecter) TableName() *MockTabler_TableName_Call {
	return &MockTabler_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *MockTabler_TableName_Call) Run(run func()) *MockTabler_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTabler_TableName_Call) Return(s string) *MockTabler_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTabler_TableName_Call) RunAndReturn(run func() string) *MockTabler_TableName_Call {
	_c.Call.Return(run)
	return _c
}
