// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Create(context1 context.Context, customer *model.Customer) error {
	ret := _mock.Called(context1, customer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = returnFunc(context1, customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCustomerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - customer *model.Customer
func (_e *MockCustomerRepository_Expecter) Create(context1 interface{}, customer interface{}) *MockCustomerRepository_Create_Call {
	return &MockCustomerRepository_Create_Call{Call: _e.mock.On("Create", context1, customer)}
}

func (_c *MockCustomerRepository_Create_Call) Run(run func(context1 context.Context, customer *model.Customer)) *MockCustomerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Customer
		if args[1] != nil {
			arg1 = args[1].(*model.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Create_Call) Return(err error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Create_Call) RunAndReturn(run func(context1 context.Context, customer *model.Customer) error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
