// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQRBookingRepository creates a new instance of MockQRBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQRBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQRBookingRepository {
	mock := &MockQRBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQRBookingRepository is an autogenerated mock type for the QRBookingRepository type
type MockQRBookingRepository struct {
	mock.Mock
}

type MockQRBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQRBookingRepository) EXPECT() *MockQRBookingRepository_Expecter {
	return &MockQRBookingRepository_Expecter{mock: &_m.Mock}
}

// FindBookingByID provides a mock function for the type MockQRBookingRepository
func (_mock *MockQRBookingRepository) FindBookingByID(ctx context.Context, id string) (*model.BookingRecord, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindBookingByID")
	}

	var r0 *model.BookingRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.BookingRecord, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.BookingRecord); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BookingRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQRBookingRepository_FindBookingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBookingByID'
type MockQRBookingRepository_FindBookingByID_Call struct {
	*mock.Call
}

// FindBookingByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQRBookingRepository_Expecter) FindBookingByID(ctx interface{}, id interface{}) *MockQRBookingRepository_FindBookingByID_Call {
	return &MockQRBookingRepository_FindBookingByID_Call{Call: _e.mock.On("FindBookingByID", ctx, id)}
}

func (_c *MockQRBookingRepository_FindBookingByID_Call) Run(run func(ctx context.Context, id string)) *MockQRBookingRepository_FindBookingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQRBookingRepository_FindBookingByID_Call) Return(bookingRecord *model.BookingRecord, err error) *MockQRBookingRepository_FindBookingByID_Call {
	_c.Call.Return(bookingRecord, err)
	return _c
}

func (_c *MockQRBookingRepository_FindBookingByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.BookingRecord, error)) *MockQRBookingRepository_FindBookingByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSeatsByBookingID provides a mock function for the type MockQRBookingRepository
func (_mock *MockQRBookingRepository) FindSeatsByBookingID(ctx context.Context, bookingID string) ([]string, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindSeatsByBookingID")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQRBookingRepository_FindSeatsByBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSeatsByBookingID'
type MockQRBookingRepository_FindSeatsByBookingID_Call struct {
	*mock.Call
}

// FindSeatsByBookingID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockQRBookingRepository_Expecter) FindSeatsByBookingID(ctx interface{}, bookingID interface{}) *MockQRBookingRepository_FindSeatsByBookingID_Call {
	return &MockQRBookingRepository_FindSeatsByBookingID_Call{Call: _e.mock.On("FindSeatsByBookingID", ctx, bookingID)}
}

func (_c *MockQRBookingRepository_FindSeatsByBookingID_Call) Run(run func(ctx context.Context, bookingID string)) *MockQRBookingRepository_FindSeatsByBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQRBookingRepository_FindSeatsByBookingID_Call) Return(strings []string, err error) *MockQRBookingRepository_FindSeatsByBookingID_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockQRBookingRepository_FindSeatsByBookingID_Call) RunAndReturn(run func(ctx context.Context, bookingID string) ([]string, error)) *MockQRBookingRepository_FindSeatsByBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// FindShowByID provides a mock function for the type MockQRBookingRepository
func (_mock *MockQRBookingRepository) FindShowByID(ctx context.Context, id string) (*model.ShowRecord, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindShowByID")
	}

	var r0 *model.ShowRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShowRecord, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShowRecord); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShowRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQRBookingRepository_FindShowByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindShowByID'
type MockQRBookingRepository_FindShowByID_Call struct {
	*mock.Call
}

// FindShowByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQRBookingRepository_Expecter) FindShowByID(ctx interface{}, id interface{}) *MockQRBookingRepository_FindShowByID_Call {
	return &MockQRBookingRepository_FindShowByID_Call{Call: _e.mock.On("FindShowByID", ctx, id)}
}

func (_c *MockQRBookingRepository_FindShowByID_Call) Run(run func(ctx context.Context, id string)) *MockQRBookingRepository_FindShowByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQRBookingRepository_FindShowByID_Call) Return(showRecord *model.ShowRecord, err error) *MockQRBookingRepository_FindShowByID_Call {
	_c.Call.Return(showRecord, err)
	return _c
}

func (_c *MockQRBookingRepository_FindShowByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.ShowRecord, error)) *MockQRBookingRepository_FindShowByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQRCodeURL provides a mock function for the type MockQRBookingRepository
func (_mock *MockQRBookingRepository) UpdateQRCodeURL(ctx context.Context, id string, qrURL string) error {
	ret := _mock.Called(ctx, id, qrURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQRCodeURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, qrURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQRBookingRepository_UpdateQRCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQRCodeURL'
type MockQRBookingRepository_UpdateQRCodeURL_Call struct {
	*mock.Call
}

// UpdateQRCodeURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - qrURL string
func (_e *MockQRBookingRepository_Expecter) UpdateQRCodeURL(ctx interface{}, id interface{}, qrURL interface{}) *MockQRBookingRepository_UpdateQRCodeURL_Call {
	return &MockQRBookingRepository_UpdateQRCodeURL_Call{Call: _e.mock.On("UpdateQRCodeURL", ctx, id, qrURL)}
}

func (_c *MockQRBookingRepository_UpdateQRCodeURL_Call) Run(run func(ctx context.Context, id string, qrURL string)) *MockQRBookingRepository_UpdateQRCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQRBookingRepository_UpdateQRCodeURL_Call) Return(err error) *MockQRBookingRepository_UpdateQRCodeURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQRBookingRepository_UpdateQRCodeURL_Call) RunAndReturn(run func(ctx context.Context, id string, qrURL string) error) *MockQRBookingRepository_UpdateQRCodeURL_Call {
	_c.Call.Return(run)
	return _c
}
