// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShowService creates a new instance of MockShowService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShowService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShowService {
	mock := &MockShowService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShowService is an autogenerated mock type for the ShowService type
type MockShowService struct {
	mock.Mock
}

type MockShowService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShowService) EXPECT() *MockShowService_Expecter {
	return &MockShowService_Expecter{mock: &_m.Mock}
}

// GetMovieById provides a mock function for the type MockShowService
func (_mock *MockShowService) GetMovieById(context1 context.Context, s string) (*model.Movie, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieById")
	}

	var r0 *model.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Movie, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Movie); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowService_GetMovieById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieById'
type MockShowService_GetMovieById_Call struct {
	*mock.Call
}

// GetMovieById is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockShowService_Expecter) GetMovieById(context1 interface{}, s interface{}) *MockShowService_GetMovieById_Call {
	return &MockShowService_GetMovieById_Call{Call: _e.mock.On("GetMovieById", context1, s)}
}

func (_c *MockShowService_GetMovieById_Call) Run(run func(context1 context.Context, s string)) *MockShowService_GetMovieById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowService_GetMovieById_Call) Return(movie *model.Movie, err error) *MockShowService_GetMovieById_Call {
	_c.Call.Return(movie, err)
	return _c
}

func (_c *MockShowService_GetMovieById_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.Movie, error)) *MockShowService_GetMovieById_Call {
	_c.Call.Return(run)
	return _c
}

// GetShows provides a mock function for the type MockShowService
func (_mock *MockShowService) GetShows(context1 context.Context, s string) ([]model.Show, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetShows")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Show, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Show); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowService_GetShows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShows'
type MockShowService_GetShows_Call struct {
	*mock.Call
}

// GetShows is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockShowService_Expecter) GetShows(context1 interface{}, s interface{}) *MockShowService_GetShows_Call {
	return &MockShowService_GetShows_Call{Call: _e.mock.On("GetShows", context1, s)}
}

func (_c *MockShowService_GetShows_Call) Run(run func(context1 context.Context, s string)) *MockShowService_GetShows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowService_GetShows_Call) Return(shows []model.Show, err error) *MockShowService_GetShows_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockShowService_GetShows_Call) RunAndReturn(run func(context1 context.Context, s string) ([]model.Show, error)) *MockShowService_GetShows_Call {
	_c.Call.Return(run)
	return _c
}
