// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQRService creates a new instance of MockQRService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQRService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQRService {
	mock := &MockQRService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQRService is an autogenerated mock type for the QRService type
type MockQRService struct {
	mock.Mock
}

type MockQRService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQRService) EXPECT() *MockQRService_Expecter {
	return &MockQRService_Expecter{mock: &_m.Mock}
}

// GenerateQR provides a mock function for the type MockQRService
func (_mock *MockQRService) GenerateQR(ctx context.Context, bookingID string) (string, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQR")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQRService_GenerateQR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateQR'
type MockQRService_GenerateQR_Call struct {
	*mock.Call
}

// GenerateQR is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockQRService_Expecter) GenerateQR(ctx interface{}, bookingID interface{}) *MockQRService_GenerateQR_Call {
	return &MockQRService_GenerateQR_Call{Call: _e.mock.On("GenerateQR", ctx, bookingID)}
}

func (_c *MockQRService_GenerateQR_Call) Run(run func(ctx context.Context, bookingID string)) *MockQRService_GenerateQR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQRService_GenerateQR_Call) Return(s string, err error) *MockQRService_GenerateQR_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQRService_GenerateQR_Call) RunAndReturn(run func(ctx context.Context, bookingID string) (string, error)) *MockQRService_GenerateQR_Call {
	_c.Call.Return(run)
	return _c
}
