// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"
	"skyfox/bookings/dto/request"
	"skyfox/bookings/model"
	"skyfox/bookings/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingService creates a new instance of MockBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingService {
	mock := &MockBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingService is an autogenerated mock type for the BookingService type
type MockBookingService struct {
	mock.Mock
}

type MockBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingService) EXPECT() *MockBookingService_Expecter {
	return &MockBookingService_Expecter{mock: &_m.Mock}
}

// Book provides a mock function for the type MockBookingService
func (_mock *MockBookingService) Book(context1 context.Context, bookingRequest request.BookingRequest) (*model.Booking, error) {
	ret := _mock.Called(context1, bookingRequest)

	if len(ret) == 0 {
		panic("no return value specified for Book")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.BookingRequest) (*model.Booking, error)); ok {
		return returnFunc(context1, bookingRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.BookingRequest) *model.Booking); ok {
		r0 = returnFunc(context1, bookingRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.BookingRequest) error); ok {
		r1 = returnFunc(context1, bookingRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_Book_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Book'
type MockBookingService_Book_Call struct {
	*mock.Call
}

// Book is a helper method to define mock.On call
//   - context1 context.Context
//   - bookingRequest request.BookingRequest
func (_e *MockBookingService_Expecter) Book(context1 interface{}, bookingRequest interface{}) *MockBookingService_Book_Call {
	return &MockBookingService_Book_Call{Call: _e.mock.On("Book", context1, bookingRequest)}
}

func (_c *MockBookingService_Book_Call) Run(run func(context1 context.Context, bookingRequest request.BookingRequest)) *MockBookingService_Book_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.BookingRequest
		if args[1] != nil {
			arg1 = args[1].(request.BookingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_Book_Call) Return(booking *model.Booking, err error) *MockBookingService_Book_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_Book_Call) RunAndReturn(run func(context1 context.Context, bookingRequest request.BookingRequest) (*model.Booking, error)) *MockBookingService_Book_Call {
	_c.Call.Return(run)
	return _c
}

// SetCustomerRepository provides a mock function for the type MockBookingService
func (_mock *MockBookingService) SetCustomerRepository(customerRepository repository.CustomerRepository) {
	_mock.Called(customerRepository)
	return
}

// MockBookingService_SetCustomerRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCustomerRepository'
type MockBookingService_SetCustomerRepository_Call struct {
	*mock.Call
}

// SetCustomerRepository is a helper method to define mock.On call
//   - customerRepository repository.CustomerRepository
func (_e *MockBookingService_Expecter) SetCustomerRepository(customerRepository interface{}) *MockBookingService_SetCustomerRepository_Call {
	return &MockBookingService_SetCustomerRepository_Call{Call: _e.mock.On("SetCustomerRepository", customerRepository)}
}

func (_c *MockBookingService_SetCustomerRepository_Call) Run(run func(customerRepository repository.CustomerRepository)) *MockBookingService_SetCustomerRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repository.CustomerRepository
		if args[0] != nil {
			arg0 = args[0].(repository.CustomerRepository)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingService_SetCustomerRepository_Call) Return() *MockBookingService_SetCustomerRepository_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBookingService_SetCustomerRepository_Call) RunAndReturn(run func(customerRepository repository.CustomerRepository)) *MockBookingService_SetCustomerRepository_Call {
	_c.Run(run)
	return _c
}
