// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRevenueService creates a new instance of MockRevenueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevenueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevenueService {
	mock := &MockRevenueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRevenueService is an autogenerated mock type for the RevenueService type
type MockRevenueService struct {
	mock.Mock
}

type MockRevenueService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevenueService) EXPECT() *MockRevenueService_Expecter {
	return &MockRevenueService_Expecter{mock: &_m.Mock}
}

// RevenueOn provides a mock function for the type MockRevenueService
func (_mock *MockRevenueService) RevenueOn(context1 context.Context, s string) (float64, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RevenueOn")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevenueService_RevenueOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevenueOn'
type MockRevenueService_RevenueOn_Call struct {
	*mock.Call
}

// RevenueOn is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRevenueService_Expecter) RevenueOn(context1 interface{}, s interface{}) *MockRevenueService_RevenueOn_Call {
	return &MockRevenueService_RevenueOn_Call{Call: _e.mock.On("RevenueOn", context1, s)}
}

func (_c *MockRevenueService_RevenueOn_Call) Run(run func(context1 context.Context, s string)) *MockRevenueService_RevenueOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRevenueService_RevenueOn_Call) Return(f float64, err error) *MockRevenueService_RevenueOn_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockRevenueService_RevenueOn_Call) RunAndReturn(run func(context1 context.Context, s string) (float64, error)) *MockRevenueService_RevenueOn_Call {
	_c.Call.Return(run)
	return _c
}
