// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// UserDetails provides a mock function for the type MockUserService
func (_mock *MockUserService) UserDetails(context1 context.Context, s string) (model.User, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for UserDetails")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UserDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserDetails'
type MockUserService_UserDetails_Call struct {
	*mock.Call
}

// UserDetails is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUserService_Expecter) UserDetails(context1 interface{}, s interface{}) *MockUserService_UserDetails_Call {
	return &MockUserService_UserDetails_Call{Call: _e.mock.On("UserDetails", context1, s)}
}

func (_c *MockUserService_UserDetails_Call) Run(run func(context1 context.Context, s string)) *MockUserService_UserDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_UserDetails_Call) Return(user model.User, err error) *MockUserService_UserDetails_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_UserDetails_Call) RunAndReturn(run func(context1 context.Context, s string) (model.User, error)) *MockUserService_UserDetails_Call {
	_c.Call.Return(run)
	return _c
}
