// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"
	"skyfox/bookings/dto/request"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Signup provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Signup(ctx context.Context, req request.SignupRequest) (*model.UserAccount, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Signup")
	}

	var r0 *model.UserAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.SignupRequest) (*model.UserAccount, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.SignupRequest) *model.UserAccount); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.SignupRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Signup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signup'
type MockAuthService_Signup_Call struct {
	*mock.Call
}

// Signup is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.SignupRequest
func (_e *MockAuthService_Expecter) Signup(ctx interface{}, req interface{}) *MockAuthService_Signup_Call {
	return &MockAuthService_Signup_Call{Call: _e.mock.On("Signup", ctx, req)}
}

func (_c *MockAuthService_Signup_Call) Run(run func(ctx context.Context, req request.SignupRequest)) *MockAuthService_Signup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.SignupRequest
		if args[1] != nil {
			arg1 = args[1].(request.SignupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Signup_Call) Return(userAccount *model.UserAccount, err error) *MockAuthService_Signup_Call {
	_c.Call.Return(userAccount, err)
	return _c
}

func (_c *MockAuthService_Signup_Call) RunAndReturn(run func(ctx context.Context, req request.SignupRequest) (*model.UserAccount, error)) *MockAuthService_Signup_Call {
	_c.Call.Return(run)
	return _c
}
