CREATE TABLE IF NOT EXISTS PAYMENTS(

    ID INT GENERATED BY DEFAULT AS IDENTITY ,
    booking_id  UUID not null,
    payment_mode varchar(20) not null,
    gateway VARCHAR(50),
    transaction_id VARCHAR(255),
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(20)  ,
    created_at TIMESTAMP,
    paid_at TIMESTAMP,
    CONSTRAINT check_payment_mode CHECK (payment_mode IN ('cash', 'online')),
    CONSTRAINT check_status CHECK (status IN ('FAILED', 'SUCCESS','PENDING')),
    CONSTRAINT bookingid UNIQUE (booking_id),
    PRIMARY KEY(ID)
    
)
