CREATE TABLE IF NOT EXISTS BOOKING_SEATS
(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    BOOKING_ID UUID REFERENCES BOOKINGS(ID),

    SEAT_ID UUID REFERENCES SEATS(ID),

    SHOW_ID UUID REFERENCES SHOW(ID),

    PRICE DECIMAL(10,2) NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
