CREATE TABLE IF NOT EXISTS SEAT_LOCK
(
    ID UUID PRIMARY KEY  DEFAULT gen_random_uuid(),

    SHOW_ID UUID NOT NULL REFERENCES SHOW(ID),

    SEAT_ID UUID NOT NULL REFERENCES SEATS(ID),

    LOCKED_BY UUID NOT NULL REFERENCES USERS(ID),

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    EXPIRES_AT TIMESTAMP NOT NULL,

    UNIQUE (SHOW_ID,SEAT_ID)

);
