CREATE TABLE IF NOT EXISTS BOOKINGS
(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    SHOW_ID UUID REFERENCES SHOW (ID),

    CUSTOMER_ID UUID REFERENCES USERS (ID),

    BOOKING_STATUS VARCHAR(20) DEFAULT 'RESERVED',

    PAYMENT_MODE VARCHAR(20),

    --PAYMENT_ID UUID REFERENCES PAYMENTS (ID),-----circular dependency 

    QR_CODE_URL TEXT,

    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,

    EXPIRES_AT TIMESTAMP,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    
    CONSTRAINT CHK_BOOKING_STATUS
        CHECK (BOOKING_STATUS IN ('RESERVED','CONFIRMED','CANCELLED','EXPIRED')),

    CONSTRAINT CHK_PAYMENT_MODE
        CHECK (PAYMENT_MODE IN ('CASH','ONLINE') OR PAYMENT_MODE IS NULL)
);
