// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package connection

import (
	"skyfox/bookings/database/common"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDBHandler creates a new instance of MockDBHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBHandler {
	mock := &MockDBHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDBHandler is an autogenerated mock type for the DBHandler type
type MockDBHandler struct {
	mock.Mock
}

type MockDBHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBHandler) EXPECT() *MockDBHandler_Expecter {
	return &MockDBHandler_Expecter{mock: &_m.Mock}
}

// Instance provides a mock function for the type MockDBHandler
func (_mock *MockDBHandler) Instance() *common.BaseDB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Instance")
	}

	var r0 *common.BaseDB
	if returnFunc, ok := ret.Get(0).(func() *common.BaseDB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.BaseDB)
		}
	}
	return r0
}

// MockDBHandler_Instance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instance'
type MockDBHandler_Instance_Call struct {
	*mock.Call
}

// Instance is a helper method to define mock.On call
func (_e *MockDBHandler_Expecter) Instance() *MockDBHandler_Instance_Call {
	return &MockDBHandler_Instance_Call{Call: _e.mock.On("Instance")}
}

func (_c *MockDBHandler_Instance_Call) Run(run func()) *MockDBHandler_Instance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBHandler_Instance_Call) Return(baseDB *common.BaseDB) *MockDBHandler_Instance_Call {
	_c.Call.Return(baseDB)
	return _c
}

func (_c *MockDBHandler_Instance_Call) RunAndReturn(run func() *common.BaseDB) *MockDBHandler_Instance_Call {
	_c.Call.Return(run)
	return _c
}
