// Code generated by mockery v2.14.1. DO NOT EDIT.

package repomocks

import (
	context "context"
	model "skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// MovieGateWay is an autogenerated mock type for the MovieGateWay type
type MovieGateWay struct {
	mock.Mock
}

// MovieById provides a mock function with given fields: ctx, id
func (_m *MovieGateWay) MovieById(ctx context.Context, id string) (*model.Movie, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Movie
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Movie); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMovieGateWay interface {
	mock.TestingT
	Cleanup(func())
}

// NewMovieGateWay creates a new instance of MovieGateWay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMovieGateWay(t mockConstructorTestingTNewMovieGateWay) *MovieGateWay {
	mock := &MovieGateWay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
