// Code generated by mockery v2.14.1. DO NOT EDIT.

package repomocks

import (
	context "context"
	model "skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// ShowRepository is an autogenerated mock type for the ShowRepository type
type ShowRepository struct {
	mock.Mock
}

// FindById provides a mock function with given fields: ctx, id
func (_m *ShowRepository) FindById(ctx context.Context, id int) (model.Show, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Show
	if rf, ok := ret.Get(0).(func(context.Context, int) model.Show); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Show)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllShowsOn provides a mock function with given fields: ctx, date
func (_m *ShowRepository) GetAllShowsOn(ctx context.Context, date string) ([]model.Show, error) {
	ret := _m.Called(ctx, date)

	var r0 []model.Show
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Show); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewShowRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewShowRepository creates a new instance of ShowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewShowRepository(t mockConstructorTestingTNewShowRepository) *ShowRepository {
	mock := &ShowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
