// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingRepository is an autogenerated mock type for the BookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// BookedSeatsByShow provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) BookedSeatsByShow(context1 context.Context, n int) int {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for BookedSeatsByShow")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(context1, n)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockBookingRepository_BookedSeatsByShow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookedSeatsByShow'
type MockBookingRepository_BookedSeatsByShow_Call struct {
	*mock.Call
}

// BookedSeatsByShow is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockBookingRepository_Expecter) BookedSeatsByShow(context1 interface{}, n interface{}) *MockBookingRepository_BookedSeatsByShow_Call {
	return &MockBookingRepository_BookedSeatsByShow_Call{Call: _e.mock.On("BookedSeatsByShow", context1, n)}
}

func (_c *MockBookingRepository_BookedSeatsByShow_Call) Run(run func(context1 context.Context, n int)) *MockBookingRepository_BookedSeatsByShow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_BookedSeatsByShow_Call) Return(n1 int) *MockBookingRepository_BookedSeatsByShow_Call {
	_c.Call.Return(n1)
	return _c
}

func (_c *MockBookingRepository_BookedSeatsByShow_Call) RunAndReturn(run func(context1 context.Context, n int) int) *MockBookingRepository_BookedSeatsByShow_Call {
	_c.Call.Return(run)
	return _c
}

// BookingAmountByShows provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) BookingAmountByShows(context1 context.Context, ints []int) float64 {
	ret := _mock.Called(context1, ints)

	if len(ret) == 0 {
		panic("no return value specified for BookingAmountByShows")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) float64); ok {
		r0 = returnFunc(context1, ints)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockBookingRepository_BookingAmountByShows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookingAmountByShows'
type MockBookingRepository_BookingAmountByShows_Call struct {
	*mock.Call
}

// BookingAmountByShows is a helper method to define mock.On call
//   - context1 context.Context
//   - ints []int
func (_e *MockBookingRepository_Expecter) BookingAmountByShows(context1 interface{}, ints interface{}) *MockBookingRepository_BookingAmountByShows_Call {
	return &MockBookingRepository_BookingAmountByShows_Call{Call: _e.mock.On("BookingAmountByShows", context1, ints)}
}

func (_c *MockBookingRepository_BookingAmountByShows_Call) Run(run func(context1 context.Context, ints []int)) *MockBookingRepository_BookingAmountByShows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_BookingAmountByShows_Call) Return(f float64) *MockBookingRepository_BookingAmountByShows_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockBookingRepository_BookingAmountByShows_Call) RunAndReturn(run func(context1 context.Context, ints []int) float64) *MockBookingRepository_BookingAmountByShows_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) Create(context1 context.Context, booking *model.Booking) error {
	ret := _mock.Called(context1, booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Booking) error); ok {
		r0 = returnFunc(context1, booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - booking *model.Booking
func (_e *MockBookingRepository_Expecter) Create(context1 interface{}, booking interface{}) *MockBookingRepository_Create_Call {
	return &MockBookingRepository_Create_Call{Call: _e.mock.On("Create", context1, booking)}
}

func (_c *MockBookingRepository_Create_Call) Run(run func(context1 context.Context, booking *model.Booking)) *MockBookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Booking
		if args[1] != nil {
			arg1 = args[1].(*model.Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_Create_Call) Return(err error) *MockBookingRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingRepository_Create_Call) RunAndReturn(run func(context1 context.Context, booking *model.Booking) error) *MockBookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
