// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShowRepository creates a new instance of MockShowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShowRepository {
	mock := &MockShowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShowRepository is an autogenerated mock type for the ShowRepository type
type MockShowRepository struct {
	mock.Mock
}

type MockShowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShowRepository) EXPECT() *MockShowRepository_Expecter {
	return &MockShowRepository_Expecter{mock: &_m.Mock}
}

// FindById provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) FindById(ctx context.Context, id int) (model.Show, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (model.Show, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) model.Show); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Show)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockShowRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockShowRepository_Expecter) FindById(ctx interface{}, id interface{}) *MockShowRepository_FindById_Call {
	return &MockShowRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockShowRepository_FindById_Call) Run(run func(ctx context.Context, id int)) *MockShowRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_FindById_Call) Return(show model.Show, err error) *MockShowRepository_FindById_Call {
	_c.Call.Return(show, err)
	return _c
}

func (_c *MockShowRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id int) (model.Show, error)) *MockShowRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllShowsOn provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) GetAllShowsOn(ctx context.Context, date string) ([]model.Show, error) {
	ret := _mock.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAllShowsOn")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Show, error)); ok {
		return returnFunc(ctx, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Show); ok {
		r0 = returnFunc(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_GetAllShowsOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllShowsOn'
type MockShowRepository_GetAllShowsOn_Call struct {
	*mock.Call
}

// GetAllShowsOn is a helper method to define mock.On call
//   - ctx context.Context
//   - date string
func (_e *MockShowRepository_Expecter) GetAllShowsOn(ctx interface{}, date interface{}) *MockShowRepository_GetAllShowsOn_Call {
	return &MockShowRepository_GetAllShowsOn_Call{Call: _e.mock.On("GetAllShowsOn", ctx, date)}
}

func (_c *MockShowRepository_GetAllShowsOn_Call) Run(run func(ctx context.Context, date string)) *MockShowRepository_GetAllShowsOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_GetAllShowsOn_Call) Return(shows []model.Show, err error) *MockShowRepository_GetAllShowsOn_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockShowRepository_GetAllShowsOn_Call) RunAndReturn(run func(ctx context.Context, date string) ([]model.Show, error)) *MockShowRepository_GetAllShowsOn_Call {
	_c.Call.Return(run)
	return _c
}
