// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUserRepository creates a new instance of MockAuthUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUserRepository {
	mock := &MockAuthUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUserRepository is an autogenerated mock type for the AuthUserRepository type
type MockAuthUserRepository struct {
	mock.Mock
}

type MockAuthUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUserRepository) EXPECT() *MockAuthUserRepository_Expecter {
	return &MockAuthUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthUserRepository
func (_mock *MockAuthUserRepository) CreateUser(ctx context.Context, user *model.UserAccount) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserAccount) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.UserAccount
func (_e *MockAuthUserRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockAuthUserRepository_CreateUser_Call {
	return &MockAuthUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockAuthUserRepository_CreateUser_Call) Run(run func(ctx context.Context, user *model.UserAccount)) *MockAuthUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UserAccount
		if args[1] != nil {
			arg1 = args[1].(*model.UserAccount)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUserRepository_CreateUser_Call) Return(err error) *MockAuthUserRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUserRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *model.UserAccount) error) *MockAuthUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockAuthUserRepository
func (_mock *MockAuthUserRepository) FindByEmail(ctx context.Context, phone string) (*model.UserAccount, error) {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.UserAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserAccount, error)); ok {
		return returnFunc(ctx, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserAccount); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockAuthUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockAuthUserRepository_Expecter) FindByEmail(ctx interface{}, phone interface{}) *MockAuthUserRepository_FindByEmail_Call {
	return &MockAuthUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, phone)}
}

func (_c *MockAuthUserRepository_FindByEmail_Call) Run(run func(ctx context.Context, phone string)) *MockAuthUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUserRepository_FindByEmail_Call) Return(userAccount *model.UserAccount, err error) *MockAuthUserRepository_FindByEmail_Call {
	_c.Call.Return(userAccount, err)
	return _c
}

func (_c *MockAuthUserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, phone string) (*model.UserAccount, error)) *MockAuthUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPhone provides a mock function for the type MockAuthUserRepository
func (_mock *MockAuthUserRepository) FindByPhone(ctx context.Context, phone string) (*model.UserAccount, error) {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhone")
	}

	var r0 *model.UserAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserAccount, error)); ok {
		return returnFunc(ctx, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserAccount); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUserRepository_FindByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPhone'
type MockAuthUserRepository_FindByPhone_Call struct {
	*mock.Call
}

// FindByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockAuthUserRepository_Expecter) FindByPhone(ctx interface{}, phone interface{}) *MockAuthUserRepository_FindByPhone_Call {
	return &MockAuthUserRepository_FindByPhone_Call{Call: _e.mock.On("FindByPhone", ctx, phone)}
}

func (_c *MockAuthUserRepository_FindByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockAuthUserRepository_FindByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUserRepository_FindByPhone_Call) Return(userAccount *model.UserAccount, err error) *MockAuthUserRepository_FindByPhone_Call {
	_c.Call.Return(userAccount, err)
	return _c
}

func (_c *MockAuthUserRepository_FindByPhone_Call) RunAndReturn(run func(ctx context.Context, phone string) (*model.UserAccount, error)) *MockAuthUserRepository_FindByPhone_Call {
	_c.Call.Return(run)
	return _c
}
