// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package movieservice

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMovieGateWay creates a new instance of MockMovieGateWay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMovieGateWay(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMovieGateWay {
	mock := &MockMovieGateWay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMovieGateWay is an autogenerated mock type for the MovieGateWay type
type MockMovieGateWay struct {
	mock.Mock
}

type MockMovieGateWay_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMovieGateWay) EXPECT() *MockMovieGateWay_Expecter {
	return &MockMovieGateWay_Expecter{mock: &_m.Mock}
}

// MovieById provides a mock function for the type MockMovieGateWay
func (_mock *MockMovieGateWay) MovieById(ctx context.Context, id string) (*model.Movie, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MovieById")
	}

	var r0 *model.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Movie, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Movie); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieGateWay_MovieById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MovieById'
type MockMovieGateWay_MovieById_Call struct {
	*mock.Call
}

// MovieById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMovieGateWay_Expecter) MovieById(ctx interface{}, id interface{}) *MockMovieGateWay_MovieById_Call {
	return &MockMovieGateWay_MovieById_Call{Call: _e.mock.On("MovieById", ctx, id)}
}

func (_c *MockMovieGateWay_MovieById_Call) Run(run func(ctx context.Context, id string)) *MockMovieGateWay_MovieById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieGateWay_MovieById_Call) Return(movie *model.Movie, err error) *MockMovieGateWay_MovieById_Call {
	_c.Call.Return(movie, err)
	return _c
}

func (_c *MockMovieGateWay_MovieById_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Movie, error)) *MockMovieGateWay_MovieById_Call {
	_c.Call.Return(run)
	return _c
}
